name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

defaults:
  run:
    working-directory: Hummingbird
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'Switch to Xcode 14 Beta'
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
